version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9091:9091"  # Discord Audio Bridge for voice-mode MCP
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - WHISPER_CPP_BASE_URL=http://whisper-stt:9000
      - DISCORD_AUDIO_BRIDGE_PORT=9091
    stdin_open: true
    tty: true
    depends_on:
      whisper-stt:
        condition: service_healthy
      piper-tts:
        condition: service_healthy

  whisper-stt:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    ports:
      - "9090:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_MODEL_PATH=/data/whisper
      - UVICORN_LOG_LEVEL=critical
      - UVICORN_ACCESS_LOG=false
    volumes:
      - whisper-models:/data/whisper
    expose:
      - "9000"
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9000/docs')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  piper-tts:
    build: ./services/piper-http
    ports:
      - "8080:8080"
    volumes:
      - piper-models:/models
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  whisper-models:
  piper-models: