version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9091:9091"  # Discord Audio Bridge for voice-mode MCP
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - WHISPER_CPP_BASE_URL=http://whisper-stt:9000
      - DISCORD_AUDIO_BRIDGE_PORT=9091
    stdin_open: true
    tty: true
    depends_on:
      - whisper-stt
      - piper-tts

  whisper-stt:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    ports:
      - "9090:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_MODEL_PATH=/data/whisper
      - UVICORN_LOG_LEVEL=error
      - UVICORN_ACCESS_LOG=false
    volumes:
      - whisper-models:/data/whisper
    expose:
      - "9000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  piper-tts:
    build: ./services/piper-http
    ports:
      - "8080:8080"
    volumes:
      - piper-models:/models

volumes:
  whisper-models:
  piper-models: