version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    stdin_open: true
    tty: true
    depends_on:
      - whisper-stt
      - piper-tts

  whisper-stt:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9090:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    expose:
      - "9000"

  piper-tts:
    build: ./services/piper-http
    ports:
      - "8080:8080"
    volumes:
      - piper-models:/models

volumes:
  whisper-models:
  piper-models: